<a href="https://colab.research.google.com/github/Naina-Kshatri/Python_Programs/blob/main/ARRAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ARRAY

In [1]:
from array import *
vals=array('i',[5,9,8,4,2])
print(vals)

array('i', [5, 9, 8, 4, 2])


In [3]:
print(vals.buffer_info())

(140684236589776, 5)


In [4]:
print(vals.typecode)

i


In [6]:
print(vals.append(5))

None


In [8]:
print(vals.remove(9))

None


In [9]:
print(vals.reverse())

None


In [10]:
vals.reverse()
print(vals)

array('i', [5, 8, 4, 2, 5])


In [11]:
print(vals[0])

5


In [12]:
from array import *
vals=array('i',[5,9,-8,4,2])
for i in range(5):
  print(vals[i])

5
9
-8
4
2


In [13]:
from array import *
vals=array('i',[5,9,-8,4,2])
for i in range(len(vals)):
  print(vals[i])

5
9
-8
4
2


In [14]:
from array import *
vals=array('i',[5,9,-8,4,2])
for e in vals:
  print(e)

5
9
-8
4
2


In [15]:
from array import *
vals=array('u',['a','e','i'])
for e in vals:
  print(e)

a
e
i


In [16]:
from array import *
vals=array('i',[5,9,8,4,2])
newArr=array(vals.typecode,(a for a in vals))
for e in newArr:
  print(e)

5
9
8
4
2


In [17]:
from array import *
vals=array('i',[5,9,8,4,2])
newArr=array(vals.typecode,(a*a for a in vals))
for e in newArr:
  print(e)

25
81
64
16
4


In [18]:
from array import *
vals=array('i',[5,9,8,4,2])
newArr=array(vals.typecode,(a for a in vals))
i=0
while i<len(newArr):
  print(newArr[i])
  i+=1

5
9
8
4
2


In [20]:
#user input array
from array import *
arr=array('i',[])
n=int(input("enter length of array"))
for i in range(n):
    x=int(input("enter value"))
    arr.append(x)
print(arr)    


enter length of array4
enter value5
enter value2
enter value1
enter value6
array('i', [5, 2, 1, 6])


In [21]:
from array import *
arr=array('i',[])
n=int(input("enter length of array"))
for i in range(n):
    x=int(input("enter value"))
    arr.append(x)
print(arr)
val=int(input("enter value for search"))
k=0
for e in arr:
  if e==val:
    print(k)
    break
  k+=1
print(arr.index(val))    

enter length of array4
enter value5
enter value1
enter value2
enter value3
array('i', [5, 1, 2, 3])
enter value for search2
2
2


MULTIDIMENSIONAL ARRAY

In [22]:
pip install numpy


In [23]:
from numpy import *
#In numpy mention the type at the end.
arr=array([1,2,3,4,5],int)
print(arr)

[1 2 3 4 5]


DIFFERENT WAYS OF CREATING ARRAY IN NUMPY:---

1)array()

2)linspace()

3)logspace()

4)arange()

5)zeros()

6)ones()

In [24]:
from numpy import *
arr=array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [25]:
print(arr.dtype)

int64


In [26]:
from numpy import *
arr=array([1,2,3,4,5.0])#here allthe values are convered into float
print(arr)

[1. 2. 3. 4. 5.]


In [27]:
from numpy import *
arr=linspace(0,15,16)#linspace(start,stop,steps)
print(arr)
#here all the values are float because we are breaking range partwise.So, normally if we divide in part,we can get a float value.

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [28]:
from numpy import *
arr=linspace(0,15,20)
print(arr)

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [29]:
from numpy import *
arr=linspace(0,15) #If we don't specify steps,it will by default divide it into 50 parts.
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [30]:
from numpy import *
arr=arange(1,15,2) #arange(first elem,last elem,steps)
print(arr)

[ 1  3  5  7  9 11 13]


In [31]:
from numpy import *
arr=logspace(1,40,5) #In logspace the spacing b/w 2 numbers will depend upon the log of it.
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [32]:
from numpy import *
arr=zeros(5,int) #zeros(size,dtype)
print(arr)

[0 0 0 0 0]


In [33]:
from numpy import *
arr=ones(5,int)
print(arr)

[1 1 1 1 1]


Copying an array in python

In [34]:
from numpy import *
arr=array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


In [35]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=array([6,1,9,3,2])
arr3=arr1 + arr2
print(arr3)

[ 7  3 12  7  7]


In [36]:
from numpy import *
arr=array([1,2,3,4,5])
print(sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [37]:
print(cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [38]:
print(max(arr))

5


In [39]:
print(log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [40]:
print(unique(arr))

[1 2 3 4 5]


In [41]:
print(sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [45]:
from numpy import *
arr1=array([2,6,8,1,3])
arr2=arr1 #here both points to same memory location i.e;aliasing
print(arr1)
print(arr2)

[2 6 8 1 3]
[2 6 8 1 3]


In [46]:
from numpy import *
arr1=array([2,6,8,1,3])
arr2=arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 6 8 1 3]
[2 6 8 1 3]
140684096951280
140684096447472


Shallow Copy(both array will depend on each other)

In [47]:
from numpy import *
arr1=array([2,6,8,1,3])
arr2=arr1.view()
arr1[1]=7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 7 8 1 3]
140684096292064
140684097179520


Deep Copy(both array is independent of each other)

In [49]:
from numpy import *
arr1=array([2,6,8,1,3])
arr2=arr1.copy()
arr1[1]=7
print(arr1)
print(arr2)

[2 7 8 1 3]
[2 6 8 1 3]


working with Mtrix in Python

In [50]:
from numpy import *
arr1=array([
             [1,2,3],    
            [4,5,6]
         ])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [51]:
print(arr1.dtype)

int64


In [52]:
print(arr1.ndim)#gives dimenions/ranking

2


In [53]:
print(arr1.shape)#gives no. of rows and columns

(2, 3)


In [54]:
print(arr1.size)#size of entire block

6


In [55]:
from numpy import *
arr1=array([
             [1,2,3],    
            [4,5,6]
         ])
arr2=arr1.flatten()#converts 2D array into 1D array
print(arr2)

[1 2 3 4 5 6]


In [56]:
from numpy import *
arr1=array([
             [1,2,3,6,2,9],
            [4,5,6,7,5,3]       

           ])
arr2=arr1.flatten()
arr3=arr2.reshape(3,4)#reshape(rows,columns)   #converts 1d array into 2d array
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [57]:
arr3=arr2.reshape(2,2,3)#create a 3D array & that 3D array will have 2 2d array & each 2D array will have 2 1D array & each 1D array will have 3 values
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


Matrices

In [58]:
from numpy import *
arr1=array([
             [1,2,3],    
            [4,5,6]
         ])
m=matrix(arr1)
print(m)
#output looks same but with this m we can perform more operations

[[1 2 3]
 [4 5 6]]


In [59]:
from numpy import *
m=matrix('1 2 3 6 ; 4 5 6 7')
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [60]:
from numpy import *
m=matrix('1 2 ; 3 6 ; 4 5 ; 6 7')
print(m)

[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [61]:
#to print diagonal elements
from numpy import *
m=matrix('1 2 3 ; 6 4 5 ; 1 6 7')
print(diagonal(m))

[1 4 7]


In [62]:
from numpy import *
m=matrix('1 2 ; 3 6 ; 4 5 ; 6 7')
print(m.min())

1


In [63]:
print(m.max())

7


In [64]:
from numpy import *
m1=matrix('1 2 3 ; 6 4 5 ; 1 6 7')
m2=matrix('1 2 3 ; 6 8 5 ; 2 6 7')
m3=m1 + m2
print(m3)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [65]:
m3=m1 * m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
